services:
  recoverysky-timezone:
    container_name: recoverysky-timezone
    platform: linux/arm64
    image: 376129859732.dkr.ecr.${AWS_REGION}.amazonaws.com/recoverysky-timezone:${ENV}
    restart: always
    ports:
      - "3838:3838"
    command: ["node", "dist/index.js", "start", "--debug"]
    networks:
      - recoverysky-network

networks:
  recoverysky-network:
    external: true

